name: LCModuleEconomy
main: github.Lucycraft.LucycraftModule.Economy.LCModuleEconomy
version: 0.0.1a
authors: [cskiwi, thisisboris]
description: After a couple of months of hosting a bukkit server, we decided to create our very own plugin, based upon the way we play minecraft.
commands:
    Economy:
        description: Basic command to access help
        usage: |
          Example: /<command> : Shows the basic help page.
    Eco:
        description: Basic command to acces help, short version
        usage: |
          Example: /<command> : Shows the basic help page.
    